"""Catálogo conceitual e oficial da loja BJ Sports."""

STORE_PRODUCTS = [
    {
        'id': 'BJJ-001',
        'sport': 'jiu-jitsu',
        'category': 'Kimonos',
        'name': 'Kimono BJ Sports Competition',
        'price': 439.90,
        'old_price': 479.90,
        'icon': '🥋',
        'image': 'img/store/kimono_preto.jpg',
        'badge': 'Oficial',
        'sizes': ['A0', 'A1', 'A2', 'A3', 'A4'],
        'description': 'Kimono de Jiu-Jitsu oficial BJ Sports. Modelagem anatômica para competição em trama leve trançada de alta durabilidade, lapela em EVA e bordados oficiais do CT Bolivar-JR.',
        'colors': [
            {
                'id': 'preto',
                'name': 'Preto',
                'hex': '#141416',
                'image': 'img/store/kimono_preto.jpg',
                'price': 459.90,
                'old_price': 499.90,
                'badge': 'Destaque'
            },
            {
                'id': 'branco',
                'name': 'Branco',
                'hex': '#ffffff',
                'image': 'img/store/kimono_branco.jpg',
                'price': 439.90,
                'old_price': 479.90,
                'badge': 'Oficial'
            },
            {
                'id': 'azul',
                'name': 'Azul Royal',
                'hex': '#0f34a2',
                'image': 'img/store/kimono_azul.jpg',
                'price': 449.90,
                'old_price': 489.90,
                'badge': 'Oficial'
            }
        ]
    },
    {
        'id': 'BJJ-004',
        'sport': 'jiu-jitsu',
        'category': 'No-Gi',
        'name': 'Rashguard Ranked Eagle (Manga Longa)',
        'price': 139.90,
        'old_price': 159.90,
        'icon': '👕',
        'image': 'img/store/rashguard_manga_longa.jpg',
        'badge': 'Lançamento',
        'sizes': ['P', 'M', 'G', 'GG', 'XG'],
        'description': 'Rashguard de alta compressão em vermelho e preto. Estampa exclusiva da águia no abdômen, marca BJ Sports e triângulo Bolivar-JR.',
        'colors': [
            {
                'id': 'preto-vermelho',
                'name': 'Preto / Vermelho',
                'hex': '#e50914',
                'image': 'img/store/rashguard_manga_longa.jpg',
                'price': 139.90,
                'old_price': 159.90,
                'badge': 'Lançamento'
            }
        ]
    },
    {
        'id': 'BJJ-005',
        'sport': 'jiu-jitsu',
        'category': 'No-Gi',
        'name': 'Fight Shorts Grappling (Preto/Vermelho)',
        'price': 129.90,
        'old_price': 149.90,
        'icon': '🩳',
        'image': 'img/store/fight_shorts_grappling.jpg',
        'badge': 'Destaque',
        'sizes': ['36', '38', '40', '42', '44', '46'],
        'description': 'Bermuda de luta sem bolsos, com logo soco no cós, grafismo lateral BJ Sports e fenda reforçada para mobilidade no No-Gi.'
    },
    {
        'id': 'BJJ-006',
        'sport': 'jiu-jitsu',
        'category': 'No-Gi',
        'name': 'Fight Shorts Pro Brasil BJ Sports',
        'price': 139.90,
        'old_price': 159.90,
        'icon': '🩳',
        'image': 'img/store/fight_shorts_pro.jpg',
        'badge': 'Edição Especial',
        'sizes': ['36', '38', '40', '42', '44', '46'],
        'description': 'Bermuda pro com faixas laterais em vermelho, inscrição JIU-JITSU, bandeira do Brasil e ajuste com cordão duplo.'
    },
    {
        'id': 'BJJ-007',
        'sport': 'jiu-jitsu',
        'category': 'Vestuário',
        'name': 'Camiseta de Treino Camuflada BJ Sports',
        'price': 89.90,
        'old_price': 109.90,
        'icon': '👕',
        'image': 'img/store/camisa_treino_camuflada.jpg',
        'badge': 'Novo',
        'sizes': ['P', 'M', 'G', 'GG', 'XG'],
        'description': 'Camiseta dry-fit oficial com detalhes camuflados em vermelho e preto. Respirabilidade máxima para o condicionamento físico.'
    },
    {
        'id': 'BJJ-008',
        'sport': 'jiu-jitsu',
        'category': 'Vestuário',
        'name': 'Camiseta Casual BJ Sports (Preta)',
        'price': 79.90,
        'old_price': 99.90,
        'icon': '👕',
        'image': 'img/store/camiseta_preta_mockup.jpg',
        'badge': 'Casual',
        'sizes': ['P', 'M', 'G', 'GG', 'XG'],
        'description': 'Camiseta 100% algodão penteado com corte moderno e branding minimalista BJ Sports.'
    },
    {
        'id': 'BJJ-009',
        'sport': 'jiu-jitsu',
        'category': 'Acessórios BJJ',
        'name': 'Faixa de Graduação BJJ',
        'price': 79.90,
        'old_price': 89.90,
        'icon': '🎗️',
        'image': 'img/store/faixa_branca.jpg',
        'badge': 'Oficial',
        'sizes': ['A0', 'A1', 'A2', 'A3', 'A4'],
        'description': 'Faixa resistente de graduação com ponteira e tarja preta/vermelha oficial adequada ao sistema de graduação IBJJF.',
        'colors': [
            {
                'id': 'branca',
                'name': 'Branca',
                'hex': '#f4f4f6',
                'image': 'img/store/faixa_branca.jpg',
                'price': 79.90,
                'old_price': 89.90,
                'badge': 'Iniciante'
            },
            {
                'id': 'azul',
                'name': 'Azul',
                'hex': '#1d4ed8',
                'image': 'img/store/faixa_azul.jpg',
                'price': 79.90,
                'old_price': 89.90,
                'badge': 'Oficial'
            },
            {
                'id': 'roxa',
                'name': 'Roxa',
                'hex': '#7e22ce',
                'image': 'img/store/faixa_roxa.jpg',
                'price': 84.90,
                'old_price': 94.90,
                'badge': 'Intermediário'
            },
            {
                'id': 'marrom',
                'name': 'Marrom',
                'hex': '#5c3a21',
                'image': 'img/store/faixa_marrom.jpg',
                'price': 84.90,
                'old_price': 94.90,
                'badge': 'Avançado'
            },
            {
                'id': 'preta',
                'name': 'Preta',
                'hex': '#18181b',
                'image': 'img/store/faixa_preta.jpg',
                'price': 89.90,
                'old_price': 99.90,
                'badge': 'Master'
            }
        ]
    },
    {
        'id': 'BJJ-010',
        'sport': 'jiu-jitsu',
        'category': 'Acessórios BJJ',
        'name': 'Bolsa Mochila Grande Respirável com Alça Removivel Muay Thai Boxe Jiu Jitsu',
        'price': 189.90,
        'old_price': 219.90,
        'icon': '🎒',
        'image': 'img/store/bolsa_mochila_respiravel.jpg',
        'badge': 'Ventilada',
        'sizes': ['Único (Grande)'],
        'description': 'Bolsa mochila esportiva grande e ultra-respirável em tela mesh de alta resistência, com alça de ombro removível e compartimento ventilado para equipamentos de Muay Thai, Boxe e Jiu-Jitsu.'
    },
    {
        'id': 'BOX-001',
        'sport': 'boxe',
        'category': 'Luvas',
        'name': 'Luva Pro Sparring 16oz',
        'price': 399.90,
        'old_price': 449.90,
        'icon': '🥊',
        'image': 'img/store/luva_pro_sparring.jpg',
        'badge': 'Destaque',
        'sizes': ['12 oz', '14 oz', '16 oz'],
        'description': 'Proteção multicamadas com espuma injetada e fecho em velcro reforçado para treinos pesados de sparring.'
    },
    {
        'id': 'BOX-002',
        'sport': 'boxe',
        'category': 'Luvas',
        'name': 'Luva Training Fit 12oz',
        'price': 249.90,
        'old_price': 289.90,
        'icon': '🥊',
        'image': 'img/store/luva_training_fit.jpg',
        'badge': 'Treino',
        'sizes': ['10 oz', '12 oz', '14 oz'],
        'description': 'Modelo versátil para treinos em saco de pancadas, manoplas e aulas técnicas de Boxe e Muay Thai.'
    },
    {
        'id': 'BOX-003',
        'sport': 'boxe',
        'category': 'Proteção',
        'name': 'Capacete de Sparring Pro',
        'price': 279.90,
        'old_price': 319.90,
        'icon': '🪖',
        'image': 'img/store/capacete_sparring.jpg',
        'badge': 'Segurança',
        'sizes': ['P', 'M', 'G'],
        'description': 'Proteção anatômica para queixo, pômulo e orelhas com regulagem tripla na nuca e topo.'
    },
    {
        'id': 'BOX-004',
        'sport': 'boxe',
        'category': 'Proteção',
        'name': 'Bandagem Elástica 4,5m (Par)',
        'price': 39.90,
        'icon': '🩹',
        'image': 'img/store/bandagem_elastica.jpg',
        'badge': 'Essencial',
        'sizes': ['Par (4,5m)'],
        'description': 'Bandagens de alta elasticidade e respirabilidade para fixação das articulações da mão e punho.'
    },
    {
        'id': 'BOX-005',
        'sport': 'boxe',
        'category': 'Proteção',
        'name': 'Protetor Bucal Moldável Dual Density',
        'price': 59.90,
        'icon': '🛡️',
        'image': 'img/store/protetor_bucal.jpg',
        'badge': 'Proteção',
        'sizes': ['Adulto'],
        'description': 'Moldagem térmica dual density com canal de respiração frontal e estojo protetor antibacteriano.'
    },
    {
        'id': 'BOX-006',
        'sport': 'boxe',
        'category': 'Treinamento',
        'name': 'Manopla Curva Focus Pad (Par)',
        'price': 189.90,
        'icon': '🎯',
        'image': 'img/store/manopla_curva.jpg',
        'badge': 'Precisão',
        'sizes': ['Par'],
        'description': 'Alvo curvo em P.U. reforçado para treinos de velocidade, combinação de golpes e manopla.'
    },
    {
        'id': 'BOX-007',
        'sport': 'boxe',
        'category': 'Treinamento',
        'name': 'Corda Speed Rope Pro',
        'price': 69.90,
        'icon': '⚡',
        'image': 'img/store/corda_speed_rope.jpg',
        'badge': 'Velocidade',
        'sizes': ['Ajustável (3m)'],
        'description': 'Corda de pular com rolamento rápido e cabo metálico encapado ajustável para alto rendimento.'
    },
    {
        'id': 'BOX-008',
        'sport': 'boxe',
        'category': 'Treinamento',
        'name': 'Saco de Pancadas 90cm Heavy Bag',
        'price': 649.90,
        'old_price': 699.90,
        'icon': '💥',
        'image': 'img/store/saco_pancadas.jpg',
        'badge': 'Heavy Duty',
        'sizes': ['90 × 30 cm'],
        'description': 'Estrutura ultra-resistente em couro ecológico com correntes e giratório de aço.'
    },
    {
        'id': 'MT-001',
        'sport': 'muay-thai',
        'category': 'Shorts',
        'name': 'Shorts de Muay Thai Pro Tradicional',
        'price': 129.90,
        'old_price': 149.90,
        'icon': '🩳',
        'image': 'img/store/shorts_muay_thai.jpg',
        'badge': 'Tailandês',
        'sizes': ['P', 'M', 'G', 'GG', 'XG'],
        'description': 'Bermuda tradicional de Muay Thai em cetim reforçado com fendas laterais profundas para flexibilidade extrema em chutes e joelhadas, e cós largo elástico.'
    },
    {
        'id': 'MT-002',
        'sport': 'muay-thai',
        'category': 'Proteção MT',
        'name': 'Caneleira de Muay Thai Pro Impact',
        'price': 269.90,
        'old_price': 299.90,
        'icon': '🦵',
        'image': 'img/store/caneleira_muay_thai.jpg',
        'badge': 'Destaque',
        'sizes': ['P', 'M', 'G'],
        'description': 'Caneleira anatômica em couro ecológico com acolchoamento denso na tíbia e peito do pé, e fecho duplo reforçado em velcro.'
    },
    {
        'id': 'MT-003',
        'sport': 'muay-thai',
        'category': 'Proteção MT',
        'name': 'Cotoveleira de Muay Thai Elastic',
        'price': 79.90,
        'icon': '💪',
        'image': 'img/store/cotoveleira_muay_thai.jpg',
        'badge': 'Oficial',
        'sizes': ['M', 'G'],
        'description': 'Cotoveleira de compressão ajustável em neoprene com proteção de gel e espuma moldada para absorção de impacto.'
    },
    {
        'id': 'MT-004',
        'sport': 'muay-thai',
        'category': 'Equipamento MT',
        'name': 'Aparador de Chutes Muay Thai Pao (Par)',
        'price': 349.90,
        'old_price': 389.90,
        'icon': '🛡️',
        'image': 'img/store/aparador_chutes_pao.jpg',
        'badge': 'Treino',
        'sizes': ['Par (Curvo)'],
        'description': 'Escudo curvo ergonômico para treinos pesados de caneladas e joelhadas, com alça de apoio e suporte duplo de antebraço.'
    },
    {
        'id': 'MMA-001',
        'sport': 'mma',
        'category': 'Luvas MMA',
        'name': 'Luva de MMA Sparring 7oz Hybrid',
        'price': 229.90,
        'old_price': 259.90,
        'icon': '🥊',
        'image': 'img/store/luva_mma_sparring.jpg',
        'badge': 'Hybrid',
        'sizes': ['P', 'M', 'G', 'GG'],
        'description': 'Luva de treino de MMA 7oz com acolchoamento reforçado nos nós dos dedos e palma aberta para troca rápida entre striking e grappling.'
    },
    {
        'id': 'MMA-002',
        'sport': 'mma',
        'category': 'Luvas MMA',
        'name': 'Luva de MMA Pro Competição 4oz',
        'price': 199.90,
        'old_price': 229.90,
        'icon': '🥊',
        'image': 'img/store/luva_mma_pro.jpg',
        'badge': 'Competição',
        'sizes': ['S', 'M', 'L', 'XL'],
        'description': 'Modelo oficial de competição 4oz em couro legítimo com palma aberta, suporte de pulso duplo e fechamento firme.'
    },
    {
        'id': 'MMA-003',
        'sport': 'mma',
        'category': 'Shorts',
        'name': 'Bermuda de Luta MMA Hybrid Pro',
        'price': 139.90,
        'old_price': 159.90,
        'icon': '🩳',
        'image': 'img/store/bermuda_mma_hybrid.jpg',
        'badge': 'Resistente',
        'sizes': ['38', '40', '42', '44', '46'],
        'description': 'Bermuda pro para MMA sem bolsos ou zíperes, com painel flexível entrepernas, fendas de mobilidade e costura tripla.'
    },
    {
        'id': 'MMA-004',
        'sport': 'mma',
        'category': 'Proteção MMA',
        'name': 'Protetor Genital Coquilha Pro MMA',
        'price': 89.90,
        'icon': '🛡️',
        'badge': 'Segurança',
        'sizes': ['P', 'M', 'G'],
        'description': 'Protetor genital anatômico com bordas em gel flexível e cúpula de alta resistência para proteção absoluta nos treinos de MMA.'
    },
]
