"""Consulta da grade do cadastro em servidor sintético local."""
import json,os
from pathlib import Path
from urllib.parse import urlparse
from playwright.sync_api import sync_playwright,expect
base=os.environ['BJ_UI_BASE_URL'].rstrip('/')
assert urlparse(base).hostname in {'127.0.0.1','localhost'}
output=Path(os.environ.get('BJ_UI_OUTPUT','/tmp/bj-registration-schedule-ui'));output.mkdir(parents=True,exist_ok=True)
results=[]
with sync_playwright() as playwright:
 browser=playwright.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox'])
 for width in (390,1440):
  for theme in ('dark','light'):
   context=browser.new_context(viewport={'width':width,'height':900})
   context.add_init_script('(function(){localStorage.setItem("bjSportsTheme", '+json.dumps(theme)+');})();')
   page=context.new_page();errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
   page.goto(base+'/login?mode=register')
   section=page.locator('#registrationClasses');plan=page.locator('#regPlan')
   expect(section).to_be_hidden()
   plan.select_option(label='Boxe')
   expect(section.locator('.registration-class-card')).to_have_count(2)
   expect(section.get_by_text('Turma lotada · consulte a academia',exact=True)).to_be_visible()
   expect(section.get_by_text('Professor: Professor de ensaio',exact=True)).to_have_count(2)
   expect(section.get_by_text('Adulto · Faixa etária não definida',exact=True)).to_have_count(2)
   page.locator('#registrationClassLocation').select_option('alpha')
   expect(section.locator('.registration-class-card')).to_have_count(1)
   expect(section.locator('h4')).to_have_text('Boxe manhã')
   page.locator('#registrationClassPeriod').select_option('noite')
   expect(section.locator('.registration-class-card')).to_have_count(0)
   expect(section.get_by_text('Nenhuma turma publicada para esta modalidade e estes filtros. Consulte a academia.',exact=True)).to_be_visible()
   plan.select_option(label='Jiu-Jitsu')
   expect(section.locator('.registration-class-card')).to_have_count(2)
   expect(page.locator('#registrationClassLocation')).to_have_value('')
   expect(page.locator('#registrationClassPeriod')).to_have_value('')
   expect(section.get_by_text('Kids · 7 a 12 anos',exact=True)).to_be_visible()
   expect(section.locator('h4').filter(has_text='Boxe')).to_have_count(0)
   assert section.locator('input[name],select[name]').count()==0
   # Uma grade extensa pode ser consultada sem alongar todo o formulário.
   original=page.request.get(base+'/api/cadastro/turmas').json()['classes']
   sample=next(group for group in original if group['modality']=='Jiu-Jitsu')
   expanded=[dict(sample,id=100+index,name=f'Turma de ensaio {index}') for index in range(6)]
   page.route('**/api/cadastro/turmas',lambda route:route.fulfill(json={'classes':expanded}))
   section.locator('[data-class-refresh]').click()
   expect(section.locator('.registration-class-card')).to_have_count(6)
   expect(section.locator('.registration-class-list')).not_to_have_attribute('open','')
   section.locator('summary').focus();page.keyboard.press('Enter')
   expect(section.locator('.registration-class-list')).to_have_attribute('open','')
   page.unroute('**/api/cadastro/turmas')
   section.locator('[data-class-refresh]').click()
   expect(section.locator('.registration-class-card')).to_have_count(2)
   section.scroll_into_view_if_needed()
   assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
   page.screenshot(path=str(output/f'horarios-{width}-{theme}.png'))
   results.append({'width':width,'theme':theme,'individual_and_filters':True,'ages_from_management':True,'large_catalog_collapsible_by_keyboard':True,'overflow':False})
   plan.select_option(label='Muay Thai')
   expect(section.locator('.registration-class-card')).to_have_count(0)
   expect(section.locator('[data-class-status]')).to_contain_text('0 turmas')
   page.locator('#btnTypeCombos').click()
   plan.select_option(label='Combo de ensaio')
   expect(section.locator('[data-class-status]')).to_have_text('Escolha as modalidades do combo para consultar suas turmas.')
   choices=page.locator('[data-combo-slot] select:not(:disabled)')
   choices.nth(0).select_option('Boxe');choices.nth(1).select_option('Jiu-Jitsu')
   expect(section.locator('.registration-class-card')).to_have_count(4)
   expect(section.locator('summary')).to_have_count(2)
   section.locator('summary').first.click()
   expect(section.locator('.registration-class-list').first).to_have_attribute('open','')
   plan.select_option(label='Aula Particular')
   expect(section).to_be_hidden();expect(page.locator('#privateInstructorField')).to_be_visible()
   expect(section.locator('.registration-class-card')).to_have_count(0)
   page.locator('#btnTypeModalidades').click()
   page.route('**/api/cadastro/turmas',lambda route:route.fulfill(status=503,body='Indisponível'))
   plan.select_option(label='Boxe')
   expect(section.locator('[data-class-status]')).to_contain_text('Não foi possível consultar')
   expect(section.locator('.registration-class-card')).to_have_count(0)
   expect(page.locator('#btnRegisterSubmit')).to_be_enabled()
   page.unroute('**/api/cadastro/turmas')
   section.locator('[data-class-refresh]').click()
   expect(section.locator('.registration-class-card')).to_have_count(2)
   expect(page.locator('#registrationClassLocation')).to_be_enabled()
   assert not errors,errors
   results.append({'width':width,'theme':theme,'combo_modalities':True,'private_professional_preserved':True,'empty_and_failure_recovery':True,'no_enrollment_fields':True})
   context.close()
 browser.close()
(output/'results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
print(json.dumps({'checks':len(results),'javascript_errors':0,'production_writes':False}))
